---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: status
  label: status
- type: text
  name: source
  label: source
- type: text
  name: url
  label: url
- type: textarea
  name: description
  label: description
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
  description: Upload image
pages:
- src/projects/webpage.md
